# Setup
title:               'Álgebra'
tagline:             'Grado en Estadística'
description:         'Página con guiones de la asignatura de Álgebra para Estadística'
url:                 'https://pedritomelenas.github.io/Algebra-Lineal'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pedro A. García Sánchez

# Gems
plugins:
  - jekyll-paginate

#gems: [jekyll-paginate]  
  
# Custom vars
version:             1.1.0

exclude:
  - .vscode/
  - .github/